version: '3.9'
services:
  accounts_db:
    container_name: accounts_db
    image: postgres
    environment:
      POSTGRES_DB: 'accounts'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - 5431:5432
    volumes:
      - ./accounts/docker-entrypoint/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    healthcheck:
      test: ["CMD-SHELL", "psql -U postgres", "pg_isready"]
      interval: 10s
      timeout: 1s
      retries: 10
    networks:
      - marketplace

  accounts_api:
    container_name: accounts_api
    build:
      context: accounts
    depends_on:
      accounts_db:
        condition: service_healthy
    ports:
      - 3001:3000
    networks:
      - marketplace
    deploy:
      resources:
        limits:
          memory: "100M"
          cpus: "0.1"
        reservations:
          memory: "50M"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/", "|| exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    env_file:
      - ./accounts/.env.prod
    command: ["node", "--max-old-space-size=90", "./dist/server.js"]

  marketplace_db:
    container_name: marketplace_db
    image: postgres
    environment:
      POSTGRES_DB: 'marketplace'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "psql -U postgres", "pg_isready"]
      interval: 10s
      timeout: 1s
      retries: 10
    networks:
      - marketplace

  marketplace_api:
    container_name: marketplace_api
    build:
      context: modular-monolithic
    depends_on:
      marketplace_db:
        condition: service_healthy
    ports:
      - 3000:3000
    networks:
      - marketplace
    deploy:
      resources:
        limits:
          memory: "500M"
          cpus: "0.5"
        reservations:
          memory: "300M"
    healthcheck:
      test: [
        "CMD",
        "curl",
        "-f",
        "--request",
        "POST",
        "--url http://localhost:3000/graphql2/",
        "--header 'Content-Type: application/json'",
        "--data '{ \"query\": \"query { sayHello }\" }'",
        "|| exit 1",
      ]
      interval: 10s
      timeout: 10s
      retries: 3
    env_file:
      - ./modular-monolithic/.env.prod
    command: ["node", "--max-old-space-size=490", "./dist/main.js"]

networks:
  marketplace:
    name: marketplace
