version: '3.9'
services:
  marketplace_dev_db:
    container_name: marketplace_dev_db
    image: postgres
    environment:
      POSTGRES_DB: 'marketplace_dev'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "psql -U postgres", "pg_isready"]
      interval: 10s
      timeout: 1s
      retries: 10
